- name: Install NGINX Gateway Fabric
  kubernetes.core.helm:
    name: ngf
    chart_ref: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
    release_namespace: nginx-gateway
    create_namespace: true
    kubeconfig: "./temp_admin.conf"
    state: present
  delegate_to: localhost 
