kubernetes_version: "v1.36"
kube_version_full: "1.36.0-1.1"
pod_network_cidr: "172.16.0.0/16"
cni_version: "v3.27.0"

helm_version: "v3.18.0"
helm_platform: "linux-arm64"
helm_archive: "helm-{{ helm_version }}-{{ helm_platform }}.tar.gz"
helm_url: "https://get.helm.sh/{{ helm_archive }}"
