---

- name: "Install Load balancer"
  hosts: lb_nodes
  become: yes
  roles:
    - swapmemory_adjust
    - control_plane_loadbalancer

- name: "Configure Master and Worker Node for Installing Kubernetes"
  hosts: Nodes
  become: yes
  roles:
   - temporary_disable
   - permanent_disable
   - container_runtime
   - kubernetes

- name: "Enable IPv4 forwarding and bridge-nf-call-iptables"
  hosts: all
  become: yes
  roles:
   - load_kernal_modules
   - sysctl_parameters

- name: "Initialize First Control Plane and ADDON"
  hosts: master_nodes[0]
  become: yes
  roles:
   - kubeadm_init
   - cni

- name: "Join other Master Nodes"
  hosts: master_nodes
  become: yes
  roles:
    - kubeadm_join_masters

- name: "Setup and Join Worker"
  hosts: worker_nodes
  become: yes
  roles:
    - kubeadm_join_workers

- name: "Setup for external loadbalancer"
  hosts: master_nodes[0]
  roles:
    - metallb
    - gatewayapi_crds
    - gateway_api_controller
    - cert-manager
    
- name: Monitoring Setup
  hosts: master_nodes[0]
  roles:
    - monitoring
